version: '3.8'

services:
  fulfillment:
    image: fulfillment-demo
    build:
      context: ./
      dockerfile: Dockerfile
    restart: 'no'
    environment:
      SPRING_PROFILES_ACTIVE: production
      JDBC_DATABASE_URL: jdbc:postgresql://postgres_db:5432/postgres?user=bart&password=51mp50n
    ports:
      - '8080:8080'
      - '5005:5005'
    expose:
      - '8080'
      - '5005'
    command:
      - '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
      - '-jar'
      - 'fulfillment.jar'
  postgres_db:
    image: postgres:16
    restart: 'always'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: bart
      POSTGRES_PASSWORD: 51mp50n
