version: '3.8'

services:
  fulfillment:
    image: fulfillment-demo
    build:
      context: ./
      dockerfile: Dockerfile
    restart: 'no'
    environment:
      SPRING_PROFILES_ACTIVE: production
      JDBC_DATABASE_URL: jdbc:postgresql://postgres_db:5432/postgres?user=bart&password=51mp50n
      RABBITMQ_AMQP_URL: 'amqp://rabbit:rabbit@rabbitmq:5672/my_vhost'
    ports:
      - '8080:8080'
      - '5005:5005'
    expose:
      - '8080'
      - '5005'
    command:
      - '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
      - '-jar'
      - 'fulfillment.jar'
  postgres_db:
    image: postgres:15
    restart: 'always'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: bart
      POSTGRES_PASSWORD: 51mp50n
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
      RABBITMQ_DEFAULT_VHOST: my_vhost
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - '5672'
      - '15672'