version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.29.2
    restart: 'always'
    volumes:
    - ${PWD}/docker-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    expose:
      - '9090'
  grafana:
    image: grafana/grafana:8.1.4
    volumes:
      - ./docker-prometheus/grafana/provisioning:/etc/grafana/provisioning
      - ./docker-prometheus/grafana/dashboards:/var/lib/grafana/dashboards
    restart: 'always'
    ports:
      - '3000:3000'
    expose:
      - '3000'