version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.25.2
    restart: 'always'
    volumes:
    - ${PWD}/docker-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    expose:
      - '9090'
  grafana:
    image: grafana/grafana:7.4.5-ubuntu
    restart: 'always'
    ports:
      - '3000:3000'
    expose:
      - '3000'